words_list = [
    ('SHOLAY', 'Classic action-adventure film about two criminals hired to capture a dacoit'),
    ('MUGHAL E AZAM', 'Epic historical drama about forbidden love in the Mughal era'),
    ('DILWALE DULHANIA LE JAYENGE', 'Romantic drama about an NRI couple, famously known as DDLJ'),
    ('LAGAAN', 'Period drama about villagers challenging British rulers to a cricket match'),
    ('DANGAL', 'Sports drama based on the life of wrestler Mahavir Singh Phogat'),
    ('PK', 'Satirical comedy-drama featuring an alien who questions religious dogmas'),
    ('KABHI KHUSHI KABHIE GHAM', 'Family drama about adoption and class differences'),
    ('RANG DE BASANTI', 'Drama linking modern youth with revolutionary freedom fighters'),
    ('TAARE ZAMEEN PAR', 'Drama about a dyslexic child and his art teacher'),
    ('ZINDAGI NA MILEGI DOBARA', 'Coming-of-age drama about three friends on a road trip in Spain'),
    ('ANDAZ APNA APNA', 'Cult comedy about two slackers caught up in a crime plot'),
    ('MOTHER INDIA', 'Epic drama about a woman\'s struggle to raise her sons'),
    ('GUIDE', 'Drama about a tour guide\'s journey of self-discovery'),
    ('CHAK DE INDIA', 'Sports drama about a disgraced hockey player coaching the national women\'s team'),
    ('SWADES', 'Drama about an NRI NASA scientist returning to his roots in India'),
    ('GANGS OF WASSEYPUR', 'Epic crime saga spanning three generations of a family'),
    ('DEVDAS', 'Romantic drama based on the classic Bengali novel'),
    ('BAJRANGI BHAIJAAN', 'Drama about a man helping a mute Pakistani girl return home'),
    ('QUEEN', 'Comedy-drama about a jilted bride\'s solo honeymoon'),
    ('BARFI', 'Romantic comedy-drama featuring a deaf and mute man'),
    ('DIL CHAHTA HAI', 'Coming-of-age drama about three friends and their relationships'),
    ('PIKU', 'Comedy-drama road trip of a father-daughter duo'),
    ('ROCKSTAR', 'Musical drama about a musician\'s rise to fame and his lost love'),
    ('KAHAANI', 'Thriller about a pregnant woman searching for her missing husband in Kolkata'),
    ('LAGE RAHO MUNNA BHAI', 'Comedy about a gangster adopting Gandhian principles'),
    ('THREE IDIOTS', 'Comedy-drama critiquing the Indian education system'),
    ('VICKY DONOR', 'Romantic comedy centered around sperm donation'),
    ('HAIDER', 'Drama adapting Shakespeare\'s Hamlet in the backdrop of Kashmir conflict'),
    ('UDAAN', 'Coming-of-age drama about a boy pursuing his dreams against his father\'s wishes'),
    ('OMKARA', 'Crime drama adapting Shakespeare\'s Othello in the Indian heartland'),
    ('BLACK FRIDAY', 'Crime drama based on the 1993 Bombay bombings'),
    ('SARFAROSH', 'Action thriller about an honest police officer fighting cross-border terrorism'),
    ('DRISHYAM', 'Thriller about a family man covering up an accidental crime'),
    ('LOOTERA', 'Period romantic drama inspired by O. Henry\'s "The Last Leaf"'),
    ('BAJIRAO MASTANI', 'Historical epic about the love story of Peshwa Bajirao and Mastani'),
    ('MASAAN', 'Drama intertwining two stories set in Varanasi'),
    ('GULLY BOY', 'Musical drama about an aspiring street rapper from Mumbai\'s slums'),
    ('ANDHADHUN', 'Black comedy thriller about a blind pianist caught in a murder mystery'),
    ('ARTICLE 15', 'Crime drama addressing caste discrimination in India'),
    ('PADMAAVAT', 'Historical drama about a Rajput queen and an invading sultan'),
    ('NEWTON', 'Dark comedy about a government clerk on election duty in a conflict-ridden jungle'),
    ('TUMBBAD', 'Horror-fantasy about a family\'s greed spanning generations'),
    ('RAAZI', 'Spy thriller about an Indian spy married into a Pakistani family'),
    ('KHOSLA KA GHOSLA', 'Comedy about a middle-class family trying to reclaim their land from a builder'),
    ('HIGHWAY', 'Drama about a girl who finds freedom after being kidnapped'),
    ('MAQBOOL', 'Crime drama adapting Shakespeare\'s Macbeth in the Mumbai underworld'),
    ('DOSTI', 'Drama about the friendship between a blind boy and a crippled boy'),
    ('MOHABBATEIN', 'Musical romance set in a strict boarding school'),
    ('COMPANY', 'Crime drama about the Mumbai underworld'),
    ('SATYA', 'Crime drama about an immigrant\'s descent into the Mumbai underworld'),
    ('ANAND', 'Drama about a terminally ill man who spreads joy to others'),
    ('PYAASA', 'Drama about a struggling poet and his search for success'),
    ('AWAARA', 'Social drama about the influence of nurture over nature'),
    ('DEEWAR', 'Crime drama about two brothers on opposite sides of the law'),
    ('SALAAM BOMBAY', 'Drama about street children in Mumbai'),
    ('HERA PHERI', 'Comedy about three poor men getting caught up in a get-rich-quick scheme'),
    ('CHUPKE CHUPKE', 'Comedy of errors involving a newly married professor'),
    ('GOLMAAL', 'Comedy about four friends who get caught up in their own lies'),
    ('JAANE BHI DO YAARO', 'Dark satire on corruption in Indian politics, bureaucracy and business'),
    ('MUNNABHAI MBBS', 'Comedy about a gangster attending medical college'),
    ('WAKE UP SID', 'Coming-of-age drama about a spoiled young man finding his purpose'),
    ('JODHA AKBAR', 'Historical romance between Mughal emperor Akbar and Rajput princess Jodha'),
    ('PAAN SINGH TOMAR', 'Biopic of an athlete who became a dacoit'),
    ('HICHKI', 'Drama about a teacher with Tourette syndrome'),
    ('KALYUG', 'Drama exposing the dark underbelly of the pornography industry'),
    ('A WEDNESDAY', 'Thriller about a common man who challenges the system'),
    ('RAANJHANAA', 'Romantic drama spanning from childhood love to political awakening'),
    ('KAMINEY', 'Crime comedy about twin brothers caught in a gang war'),
    ('DEV D', 'Modern take on the classic novel Devdas'),
    ('SHAHID', 'Biopic of lawyer and human rights activist Shahid Azmi'),
    ('HAZAARON KHWAISHEIN AISI', 'Drama set against the backdrop of the 1970s Indian Emergency'),
    ('SHOR IN THE CITY', 'Dark comedy about the lives of three men in Mumbai'),
    ('OYE LUCKY LUCKY OYE', 'Comedy based on the real-life thief Devinder Singh'),
    ('JOHNNY GADDAAR', 'Neo-noir thriller about betrayal and deception'),
    ('TALVAR', 'Crime drama based on the 2008 Noida double murder case'),
    ('BADLAPUR', 'Thriller about a man seeking revenge for his family\'s murder'),
    ('JAB WE MET', 'Romantic comedy about two strangers who meet on a train'),
    ('GURU', 'Drama inspired by the life of business tycoon Dhirubhai Ambani'),
    ('FASHION', 'Drama exploring the dark side of the fashion industry'),
    ('LIFE IN A METRO', 'Ensemble drama about life and relationships in Mumbai'),
    ('FANAA', 'Romantic thriller about a tourist guide and a blind girl'),
    ('DELHI BELLY', 'Adult comedy about three roommates who get caught in a crime plot'),
    ('RANG DE BASANTI', 'Drama linking modern youth with revolutionary freedom fighters'),
    ('ROCKET SINGH SALESMAN OF THE YEAR', 'Comedy-drama about an idealistic salesman'),
    ('WATER', 'Drama about the plight of widows in colonial India'),
    ('DHOBI GHAT', 'Drama interweaving the lives of four people in Mumbai'),
    ('AIRLIFT', 'Drama based on the evacuation of Indians from Kuwait during the Gulf War'),
    ('PINK', 'Social thriller highlighting the struggles faced by women in India'),
    ('KAPOOR AND SONS', 'Family drama about a dysfunctional family'),
    ('NEERJA', 'Biopic of flight attendant Neerja Bhanot'),
    ('SPECIAL 26', 'Heist drama based on the 1987 Opera House heist'),
    ('ROCKET SINGH SALESMAN OF THE YEAR', 'Comedy-drama about an idealistic salesman'),
    ('DEV D', 'Modern adaptation of the classic novel Devdas'),
    ('PIKU', 'Comedy-drama about a father-daughter relationship'),
    ('HAIDER', 'Modern-day adaptation of Shakespeare\'s Hamlet set in Kashmir'),
    ('GANGS OF WASSEYPUR', 'Epic crime saga spanning three generations'),
    ('MASAAN', 'Drama intertwining two stories set in Varanasi'),
    ('SHAHID', 'Biopic of lawyer and human rights activist Shahid Azmi'),
    ('THE LUNCHBOX', 'Romance between a lonely housewife and an older man via a misdelivered lunchbox'),
    ('HIGHWAY', 'Drama about a girl who finds freedom after being kidnapped'),
    ('QUEEN', 'Comedy-drama about a girl who goes on her honeymoon alone after being jilted'),
    ('LIPSTICK UNDER MY BURKHA', 'Drama about the secret lives of four women in a small town'),
    ('NEWTON', 'Dark comedy about a government clerk on election duty in a conflict-ridden area'),
    ('TUMBBAD', 'Horror-fantasy about a family\'s greed for a hidden treasure'),
    ('ANDHADHUN', 'Black comedy thriller about a blind pianist caught in a crime plot'),
    ('BADHAAI HO', 'Comedy-drama about a middle-aged couple expecting a baby'),
    ('ARTICLE 15', 'Crime drama addressing caste discrimination'),
    ('GULLY BOY', 'Musical drama about an aspiring street rapper'),
    ('SUPER 30', 'Biopic of mathematician Anand Kumar and his educational program'),
    ('BALA', 'Comedy-drama about a young man struggling with premature balding'),
    ('CHHICHHORE', 'Drama about college friends reconnecting after a tragedy'),
    ('WAR', 'Action thriller about a soldier hunting down his mentor'),
    ('KABIR SINGH', 'Romantic drama about a surgeon dealing with heartbreak'),
    ('GOOD NEWWZ', 'Comedy-drama about a mix-up in IVF treatment'),
    ('TAANAJI', 'Historical action film about the Maratha warrior Tanaji Malusare'),
    ('THAPPAD', 'Drama about a woman reevaluating her marriage after being slapped by her husband'),
    ('LUDO', 'Ensemble dark comedy about the intersecting lives of four people'),
    ('GULABO SITABO', 'Comedy-drama about a landlord and his tenant in Lucknow'),
    ('PAGGLAIT', 'Comedy-drama about a young widow finding her identity'),
    ('SHERNI', 'Drama about a forest officer dealing with man-animal conflict'),
    ('SARDAR UDHAM', 'Biopic of freedom fighter Sardar Udham Singh'),
    ('THE WHITE TIGER', 'Drama based on the novel about an ambitious driver in India'),
    ('MIMI', 'Drama about a surrogate mother and the complexities of surrogacy'),
    ('ATRANGI RE', 'Romantic drama about a love triangle across different time periods'),
    ('BELL BOTTOM', 'Spy thriller inspired by true events from the 1980s'),
    ('83', 'Sports drama about India\'s victory in the 1983 Cricket World Cup'),
    ('SHERSHAAH', 'Biopic of Captain Vikram Batra, a Kargil war hero'),
    ('BADHAAI DO', 'Comedy-drama about a marriage of convenience between a gay man and a lesbian'),
    ('JUGJUGG JEEYO', 'Family drama about the complexities of relationships'),
    ('BHOOL BHULAIYAA 2', 'Comedy horror sequel about a haunted mansion'),
    ('BRAHMASTRA', 'Fantasy adventure about a young man discovering his powers'),
    ('DRISHYAM 2', 'Thriller sequel continuing the story of a man covering up a crime'),
    ('KGF CHAPTER 2', 'Action sequel about a gangster\'s rise to power'),
    ('PATHAAN', 'Action thriller about a RAW agent facing a dangerous enemy'),
    ('TU JHOOTHI MAIN MAKKAR', 'Romantic comedy about the complexities of modern relationships'),
    ('ROCKY AUR RANI KI PREM KAHANI', 'Romantic drama about a couple from different cultural backgrounds'),
    ('RAKSHA BANDHAN', 'Family drama about the bond between siblings'),
    ('JAWAN', 'Action thriller about a man seeking justice for his family'),
    ('GANGUBAI KATHIAWADI', 'Biopic of a powerful brothel owner and political figure'),
    ('BHOOL BHULAIYAA 2', 'Comedy horror sequel about a haunted mansion'),
    ('LAL SINGH CHADDHA', 'Drama adapting "Forrest Gump" in an Indian context'),
    ('RAM SETU', 'Action adventure about an archaeologist on a quest to find a mythological bridge'),
    ('EK VILLAIN RETURNS', 'Action thriller sequel about a series of murders'),
    ('PHONE BHOOT', 'Comedy horror about three ghostbusters starting a business'),
    ('DOBAARAA', 'Science fiction thriller about time travel and parallel realities'),
    ('DASVI', 'Social comedy about an illiterate politician attempting to pass 10th grade'),
    ('LOST', 'Mystery thriller about a journalist searching for a missing person'),
    ('MONICA O MY DARLING', 'Neo-noir crime comedy about a murder plot in a tech company'),
    ('JUNGLEE', 'Action adventure about a man protecting elephants from poachers'),
    ('MARDAANI 2', 'Crime thriller about a police officer tracking a serial rapist'),
    ('CHHAPAAK', 'Biopic about an acid attack survivor'),
    ('RASHMI ROCKET', 'Sports drama about a sprinter facing gender testing'),
    ('KARTHIKEYA 2', 'Mystery thriller about a young man investigating ancient secrets'),
    ('SHYAM SINGHA ROY', 'Romantic drama spanning different time periods'),
    ('SARDAR KA GRANDSON', 'Family drama about a man fulfilling his grandmother\'s last wish'),
    ('BHUJ: THE PRIDE OF INDIA', 'War drama based on the 1971 Indo-Pak war'),
    ('TOOFAN', 'Sports drama about a boxer\'s journey to redemption'),
    ('BHOOL BHULAIYAA 2', 'Comedy horror sequel about a haunted mansion'),
    ('LAL SINGH CHADDHA', 'Drama adapting "Forrest Gump" in an Indian context'),
    ('RAKSHA BANDHAN', 'Family drama about the bond between siblings'),
    ('BELL BOTTOM', 'Spy thriller inspired by true events from the 1980s'),
    ('83', 'Sports drama about India\'s victory in the 1983 Cricket World Cup'),
    ('SHERSHAAH', 'Biopic of Captain Vikram Batra, a Kargil war hero'),
    ('BADHAAI DO', 'Comedy-drama about a marriage of convenience between a gay man and a lesbian'),
    ('JUGJUGG JEEYO', 'Family drama about the complexities of relationships'),
    ('ROCKY AUR RANI KI PREM KAHANI', 'Romantic drama about a couple from different cultural backgrounds'),
    ('BRAHMASTRA', 'Fantasy adventure about a young man discovering his powers'),
    ('DRISHYAM 2', 'Thriller sequel continuing the story of a man covering up a crime'),
    ('KGF CHAPTER 2', 'Action sequel about a gangster\'s rise to power'),
    ('PATHAAN', 'Action thriller about a RAW agent facing a dangerous enemy'),
    ('TU JHOOTHI MAIN MAKKAR', 'Romantic comedy about the complexities of modern relationships'),
    ('JAWAN', 'Action thriller about a man seeking justice for his family'),
    ('GANGUBAI KATHIAWADI', 'Biopic of a powerful brothel owner and political figure'),
    ('BHOOL BHULAIYAA 2', 'Comedy horror sequel about a haunted mansion')
]
